config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'static_pages#home'

  get '/explore', to:  'static_pages#explore', as: :explore

  # creating RESTful routes for my color palettes
  get '/palettes', to: 'palettes#index', as: :palettes

  get 'palettes/new', to: 'palettes#new', as: :new

  post '/palettes', to: 'palettes#create'

  get '/palettes/:id', to: 'palettes#show', as: :palette

  get '/palettes/:id/edit', to: 'palettes#edit', as: :edit

  patch 'palettes/:id', to: 'palettes#update', as: :update

  delete 'palettes/:id', to: 'palettes#destroy', as: :delete
end

app/models/color.rb
class Color < ActiveRecord::Base


  def self.json
    @json = Color.all.to_json
  end
end

app/models/palette.rb
class Palette < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :palettes, dependent: :destroy
  validates :user_name, presence: true
  validates :password, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :user_name
  end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
    @color = Color.random
  end
end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  def index
    all_palettes = Palette.where(user_id: current_user.id)
    @palettes = all_palettes.order(:score)
  end

  def show
    @palette = Palette.find(params[:id])
  end

  def new
    @palette = current_user.palettes.new
  end

  def create
    @palette = current_user.palettes.new(palette_params)
    @palette.save
    redirect_to @palette
  end

  def edit
    @palette = Palette.find(params[:id])
  end

  def update
    @palette = Palette.find(params[:id])
    @palette.update_attributes(palette_params)
    redirect_to palette_path
  end

  def destroy
    Palette.find(params[:id]).destroy
    redirect_to '/palettes'
  end

  private

  def palette_params
    params.require(:palette).permit(:name, :primary_name,
                                    :secondary_name, :dark_primary,
                                    :light_primary, :primary,
                                    :secondary, :text_color)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def explore
    @palettes = Palette.all

  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_filter :configure_sign_up_params, only: [:create]
  # before_filter :configure_account_update_params, only: [:update]
    before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Flash Messages for Bootstrap
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-error',
    alert: 'alert-block',
    notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type, flash_type.to_s)
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-info alert-dismissable fade-in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/views/colors/index.html.haml
%p= @color

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Material Design Color", root_path, class: "navbar-brand"
    .collapse.navbar-collapse#navbar-collapse
      %ul.nav.navbar-nav.navbar-right= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  = link_to "Explore", explore_path
- if user_signed_in?
  %li
    = link_to current_user.user_name, palettes_path
  %li
    = link_to "Sign-Out", destroy_user_session_path, method: :delete
- else
  %li
    = link_to "Sign-In", new_user_session_path
  %li
    = link_to "Sign-Up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{ :name => 'viewport', :content => 'width=device-width, maximum-scale=1.0' }
    %title Material Design Colors
    =csrf_meta_tags
    :javascript
      colorsJson = #{Color.json}
    %link{rel: "stylesheet", href:"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700", type:"text/css"}
    %link{href:"https://fonts.googleapis.com/icon?family=Material+Icons", rel:"stylesheet"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true


  %body
    .overlay
      %h2
    .backgrounds
      .background1
      .background2
      .background3
      .background4
    %header= render 'layouts/navigation'
    %main
      = yield
      = flash_messages

app/views/palettes/_saved_palettes.html.haml
.savedPalette
  .info
    %span.name.left #{@palette.name}
    %span.created_at.right #{@palette.created_at.strftime("%b. %d %Y")}
  .fontColors
    - if @palette.text_color == "true"
      .showBox.primary.primaryLightBack{style: "background: #{@palette.light_primary}"}
        .cc.colorStyle= "Primary: " << @palette.primary_name.capitalize
        .cc.hexCopy= @palette.light_primary
      .showBox.primary.primaryBack{style: "background: #{@palette.primary}"}
        .cc.colorStyle= "Primary: " << @palette.primary_name.capitalize
        .cc.hexCopy= @palette.primary
      .showBox.primary.primaryDarkBack{style: "background: #{@palette.dark_primary}"}
        .cc.colorStyle= "Primary: " << @palette.primary_name.capitalize
        .cc.hexCopy= @palette.dark_primary
      .showBox.accentBack{style: "background: #{@palette.secondary}"}
        .cc.colorStyle= "Secondary: " << @palette.secondary_name.capitalize
        .cc.hexCopy= @palette.secondary
    - else
      .showBox.primary.primaryLightBack{style: "background: #{@palette.light_primary}"}
        .colorStyle= "Primary: " << @palette.primary_name.capitalize
        .hexCopy= @palette.light_primary
      .showBox.primary.primaryBack{style: "background: #{@palette.primary}"}
        .colorStyle= "Primary: " << @palette.primary_name.capitalize
        .hexCopy= @palette.primary
      .showBox.primary.primaryDarkBack{style: "background: #{@palette.dark_primary}"}
        .colorStyle= "Primary: " << @palette.primary_name.capitalize
        .hexCopy= @palette.dark_primary
      .showBox.accentBack{style: "background: #{@palette.secondary}"}
        .colorStyle= "Secondary: " << @palette.secondary_name.capitalize
        .hexCopy= @palette.secondary
  -if current_page?(palette_path)
    .fontColors
      - if @palette.text_color == "true"
        .showBox.primaryTextL
          .textStyle Primary Text
          .hexCopy #FFFFFF
        .showBox.secondaryTextL
          .textStyle Secondary Text/Icons
          .hexCopy #BCBCBC
        .showBox.disabledTextL
          .textStyle Disabled/Hint Text
          .hexCopy #646464
        .showBox.dividerTextL
          .textStyle Dividers
          .hexCopy #3C3C3C
      - else
        .showBox.primaryTextD
          .textStyle Primary Text
          .hexCopy #212121
        .showBox.secondaryTextD
          .textStyle Secondary Text/Icons
          .hexCopy #f7f7f7
        .showBox.disabledTextD
          .textStyle Disabled/Hint Text
          .hexCopy #9b9b9b
        .showBox.dividerTextD
          .textStyle Dividers
          .hexCopy #3c3c3c
  .bottomBorder

app/views/palettes/_user_palettes.html.haml
.row
  - @palettes.each do |palette|
    -# .col-md-1
    =link_to palette, {class: "col-md-6"} do
      .savedPaletteContainer
        .colors
          .primaryLightBack{style: "background: #{palette.light_primary}"}
          .primaryBack{style: "background: #{palette.primary}"}
          .primaryDarkBack{style: "background: #{palette.dark_primary}"}
          .accentBack{style: "background: #{palette.secondary}"}
        .info
          %span.name #{palette.name}
          -if current_page?(explore_path)
            %span by:
            %span.created_by #{User.find(palette.user_id).user_name}
          %span.created_at.pull-right #{palette.created_at.strftime("%b. %d %Y")}
      -# .col-md-1
      -# %br/

app/views/palettes/edit.html.haml
.show
  - if @palette.user_id == current_user.id
    %h1 Click a color to edit:
    =render "saved_palettes.html.haml"

    = form_for @palette, html: {class: "form-horizontal"} do |m|
      %h2.hidden.updateMessage
      .form-group.hidden{id: "paletteName"}
        = m.label :name, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :name, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :primary_name, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :primary_name, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :secondary_name, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :secondary_name, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :dark_primary, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_area :dark_primary, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :light_primary, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :light_primary, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :primary, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :primary, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :secondary, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :secondary, class: "form-control"
      %br/
      .form-group.hidden
        = m.label :text_color, class: "col-sm-2 control-label"
        .col-sm-8
          = m.text_field :text_color, class: "form-control"
      %br/
      .form-group.hidden{id: "paletteSubmit"}
        .col-sm-offset-2.col-sm-8#paletteSubmit
          = m.submit "Submit", :class => "btn btn-warning"

    :javascript
      console.log(#{@palette.text_color});
      edit();
      if (#{@palette.text_color} === true){
        $('.fontColors').css('color', 'rgba(255,255,255,1)');
      } else {
        console.log('workin');
        $('.fontColors').css('color', 'rgba(0,0,0,.87)');
      }


  - else
    .jumbotron.denied
      %h1 Access Denied
      %h2 Can't touch this
      = image_tag "https://vaminidotworpressdotcomdotorg.files.wordpress.com/2013/05/hammertime-o.gif"

app/views/palettes/index.html.haml
.container-fluid
  .header
    %h1 Your Saved Color Schemes
    =link_to "create new", 'palettes/new', {class: 'btn btn-success center pull-right'}
  .savedPalettes
    =render "user_palettes"

app/views/palettes/new.html.haml
%h1 New Palette
%h2

%ul{class: "colorBoxes"}

.primarySelected
.secondarySelected


= form_for @palette, html: {class: "form-horizontal"} do |m|
  .form-group.hidden{id: 'paletteName'}
    = m.label :name, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :name, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :primary_name, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :primary_name, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :secondary_name, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :secondary_name, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :dark_primary, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_area :dark_primary, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :light_primary, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :light_primary, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :primary, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :primary, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :secondary, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :secondary, class: "form-control"
  %br/
  .form-group.hidden
    = m.label :text_color, class: "col-sm-2 control-label"
    .col-sm-8
      = m.text_field :text_color, class: "form-control"
  %br/
  .form-group.hidden{id: 'paletteSubmit'}
    .col-sm-offset-2.col-sm-8
      = m.submit "Submit", :class => "btn btn-warning newSubmit"

:javascript
  makePalette("primary");
  backgroundManipulation();
  $('h2').text('Select Your Primary Color:')
  .hide().fadeIn(1500);

app/views/palettes/show.html.haml
.container-fluid
  .show
    .header
      %h1 Show Palette
      - if @palette.user_id == current_user.id
        =link_to "Delete", delete_path, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-warning btn-lg pull-right"
        =link_to "Edit", edit_path, :class => "btn btn-success btn-lg pull-right"
    %br/
    =render "saved_palettes"
    :javascript
      if (#{@palette.text_color} === true){
          $('.fontColors').css('color', 'rgba(255,255,255,1)');
        } else {
          console.log('workin');
          $('.fontColors').css('color', 'rgba(0,0,0,.87)');
        }

app/views/static_pages/explore.html.haml
%h1 Color Schemes from All Users
.savedPalettes
  =render "palettes/user_palettes"

app/views/static_pages/home.html.haml
:css
  body{
    background: url('http://www.topofandroid.com/wp-content/uploads/2015/05/Android-L-Material-Design-Wallpapers-5.png');
  }

.jumbotron
  .introText
    %h1 Material Design Color Scheme Generator
    %h3 Find a bold, vibrant palette for your next design project.
    -if user_signed_in?
      = link_to "Browse All", explore_path, class: "btn btn-large btn-primary"
      = link_to "Create New",  new_path, class: "btn btn-large btn-primary"
    -else
      = link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary"
      = link_to "Sign in",      new_user_session_path, class: "btn btn-large btn-primary"

.colorCopy.well
  .firstRow
    .colorCircle
    .colorText
      %h2 What is Material Design?
      %p Material design is a design language created by Google in 2014.  It emphasizes the use of striking colors, depth, and smooth animations and transitions to create a seamless UX.
      %p Color in material design is inspired by strong hues juxtaposed with muted environments, deep shadows, and bright highlights. Material takes cues from contemporary architecture, road signs, pavement marking tape, and athletic courts. Color should be unexpected and vibrant.

  %br/
  %p One of the easiest way to ruin the users experience in your project is through the wrong color choice.  On the other hand, having an attractive color scheme is one of the best ways to add polish to your site or app.
  %p This application uses the Material Design language to assist you in finding the color scheme that matches the theme of your application.
  %p Each color palette is made up of 1 principal color, 2 additional shades of that color, and an accent to make important elements stand out.
  %p You can easily save and edit your color schemes for later use and explore the palettes created by other users.

  %h2 Experiment and Be Bold!

  -# %p Opaque material promotes content, whereas translucent material confuses focus and content’s ability to be manipulated.
  -# %p Toolbars and large color blocks should have your primary color.  Don't be afraid to use colors on large fields.
%footer{class: "footer bottom"}
  .text-muted
    %span Jamie King
    %a{:href => "https://twitter.com/jking0120"}
      %i.fa.fa-twitter.fa-2x
    %a{:href => "https://github.com/king0120"}
      %i.fa.fa-github.fa-2x
    %a{:href => "https://linkedin.com/in/jamieking0"}
      %i.fa.fa-linkedin-square.fa-2x